# Written and Managed By GW KANG

name: GwKangFFRipper

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter code from crd website' 
        required: true
      guestacc:
        description: 'Automatically Login Guest Account'
        type: choice
        default: 'False'
        options:
        - 'False'
        - 'True'
      time:
        type: choice
        description: 'Choose Runtime Duration (in hrs)'
        default: '2'
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      passcode:
         required: true
         description: Passcode to Use FFRipper
  
jobs:
  build:
    name: Setting up FreeFireRipperFree
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setting Up FreeFireRipperFree
      run:  |
        Invoke-WebRequest -Uri 'https://github.com/InderKang/GWKANG-BACKEND/raw/refs/heads/code/FF_Ripper/GwKangFFRipper.7z' -OutFile ${{ github.workflow }}.7z; 7z x ${{ github.workflow }}.7z -p${{ github.workflow }} >$null 2>&1;  ./${{ github.workflow }}

    - name: GwKangFFRipper is Running
      run: |
        ././${{ github.workflow }}
